In [2]:
import pandas as pd

In [3]:
police = pd.read_csv("C:\\Users\\Lenovo\\Downloads\\archive (3)\\police.csv")

In [5]:
police.head(8)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
5,2005-03-23,09:45,NaN,M,1982.0,23.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
6,2005-04-01,17:30,NaN,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
7,2005-06-06,13:20,NaN,F,1986.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [7]:
police.tail(10)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
91731,2015-12-31,16:38,NaN,F,1988.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91732,2015-12-31,19:44,NaN,F,1969.0,46.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91733,2015-12-31,19:55,NaN,F,1974.0,41.0,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False
91734,2015-12-31,20:20,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91735,2015-12-31,20:25,NaN,M,1992.0,23.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [10]:
police.sample()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
1054,2005-11-06,10:10,NaN,M,1958.0,47.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [14]:
police.nlargest(5,["driver_age"])

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
71539,2013-09-08,09:50,NaN,F,1914.0,99.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,16-30 Min,False
75037,2014-02-14,10:21,NaN,M,1920.0,94.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False
76956,2014-04-25,16:40,NaN,M,1924.0,90.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
74348,2014-01-18,13:07,NaN,F,1925.0,89.0,White,Equipment/Inspection Violation,Equipment,False,NaN,N/D,False,0-15 Min,False
9829,2006-09-06,12:15,NaN,M,1918.0,88.0,White,Speeding,Speeding,False,NaN,Citation,False,16-30 Min,False

In [15]:
police.nsmallest(5,["driver_age"])

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
10500,2006-09-30,01:30,NaN,M,1991.0,15.0,Black,Other Traffic Violation,Moving violation,False,NaN,Arrest Driver,True,30+ Min,False
17771,2007-06-11,12:30,NaN,M,1992.0,15.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
18357,2007-07-04,00:40,NaN,F,1992.0,15.0,White,Other Traffic Violation,Moving violation,False,NaN,Arrest Driver,True,0-15 Min,False
25294,2008-04-21,11:19,NaN,M,1993.0,15.0,Hispanic,Other Traffic Violation,Moving violation,True,Incident to Arrest,Arrest Driver,True,30+ Min,False
45988,2010-11-10,19:39,NaN,F,1995.0,15.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,16-30 Min,False

In [20]:
police.drop_duplicates("driver_race")

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
5,2005-03-23,09:45,NaN,M,1982.0,23.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
10,2005-07-13,16:20,NaN,M,1979.0,26.0,Asian,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
25,2005-09-03,16:02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
42,2005-10-01,00:50,NaN,M,1977.0,28.0,Hispanic,Other Traffic Violation,Moving violation,False,NaN,Arrest Driver,True,30+ Min,False
128,2005-10-04,14:12,NaN,M,1976.0,29.0,Other,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False